[package]
name = "podz"
version = "0.1.0"
edition = "2021"

[dependencies]
podz_runtime = { workspace = true }
clap = { version = "4.5.20", features = ["cargo", "derive"] }
yaml-rust2 = "0.9.0"
home = "0.5.9"

[[bin]]
name = "podz"
path = "main.rs"
doc = false
