[package]
name = "podz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
home = "0.5.9"
yaml-rust2 = "0.9.0"

[[bin]]
name = "podz"
path = "main.rs"
doc = false
